### ISSUE TITLE
Stopped working locally

### ISSUE THREAD

**Issue by seanhudson** [geocoder-php/GeocoderLaravel#64]
I'm sure it's a problem on my end, but I'm having problems debugging.

I have it using either a Google Maps API Key with a fallback of Bing Maps API. It was working on my local machine, but it stopped. However, it does work in a remote staging site.

`$location = "boulder, co";`
`$address_collection = Geocoder::geocode($location)->dump('geojson');`

I'm getting the message:

`ChainNoResult in Chain.php line 56:`
`No provider could geocode address: "boulder, co".`

When it was working, I had my local environment setup through XAMPP. Now I'm just using Homebrew to set up a new local environment. I mention this in case it might be something outside the package and my code.

Again, it's working on a staging site. Same code.

**Comment by mikebronner** [comment]
Hi @seanhudson, this is a Mac issue. You will need to use Homestead (not Valet). The core of the problem is the version of OpenSSL installed on OS X by default, which is not up-to-date and won't handle https URLs correctly.

You can try installing curl via home-brew to get around this: http://stackoverflow.com/questions/39116617/os-x-10-11-6-el-capitan-sslread-return-error-9841

Let me know how it works out for you. :) Good luck!
